import { motion } from 'framer-motion';
import { useIntersection } from '../../hooks/useIntersection';
import Card from '../ui/Card';
import Avatar from '../ui/Avatar';

export default function Traction() {
    const [ref, isVisible] = useIntersection({ threshold: 0.1 });

    const quotes = [
        { name: "Sarah Jennings", role: "Journalist", quote: "Finally, a place where the comments aren't generated by an LLM trained on Wikipedia. HumanHub feels like the internet from 2012 again." },
        { name: "Dr. Aris Chen", role: "AI Ethics Researcher", quote: "Their multi-modal detection pipeline is robust. They're solving the dead internet problem practically while others write academic papers about it." },
        { name: "Marcus Webb", role: "Venture Capitalist", quote: "A massive TAM. Every major publisher and social network will eventually need to license this backend API to survive." }
    ];

    return (
        <section className="py-32 bg-brand-bg relative overflow-hidden" ref={ref}>
            <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-brand-success/5 rounded-full blur-[150px] pointer-events-none"></div>

            <div className="max-w-[1400px] mx-auto px-4 lg:px-8 relative z-10">
                 <div className="text-center mb-16">
                     <h2 className="text-3xl font-playfair font-bold mb-4">What People Are Saying</h2>
                     <p className="text-brand-muted">Early reception from our beta cohort and industry advisors.</p>
                 </div>

                 <div className="grid md:grid-cols-3 gap-6">
                     {quotes.map((q, i) => (
                          <motion.div 
                              key={i}
                              initial={{ opacity: 0, y: 20 }}
                              animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
                              transition={{ duration: 0.5, delay: i * 0.1 }}
                          >
                              <Card className="h-full flex flex-col justify-between">
                                  <p className="text-brand-text mb-8 leading-relaxed">"{q.quote}"</p>
                                  <div className="flex items-center gap-3">
                                      <Avatar size="md" />
                                      <div>
                                          <div className="text-sm font-bold text-white">{q.name}</div>
                                          <div className="text-xs text-brand-muted">{q.role}</div>
                                      </div>
                                  </div>
                              </Card>
                          </motion.div>
                     ))}
                 </div>

                 <div className="mt-20 border-t border-white/5 pt-12 text-center opacity-60">
                     <p className="text-xs font-mono text-brand-muted uppercase mb-6 tracking-wider">Advised / Covered By</p>
                     <div className="flex flex-wrap justify-center gap-12 text-xl font-playfair font-bold text-white/50">
                         <span>TechCrunch</span>
                         <span>Y Combinator</span>
                         <span>Wired</span>
                         <span>The Verge</span>
                     </div>
                 </div>
            </div>
        </section>
    );
}
