from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import random
import os

app = FastAPI(
    title="HumanHub AI Detection Service",
    description="Microservice for detecting AI-generated text, media, and bot behavior.",
    version="1.0.0"
)

# Models
class TextAnalyzeRequest(BaseModel):
    text: str

class MediaAnalyzeRequest(BaseModel):
    urls: List[str]

class BehaviorAnalyzeRequest(BaseModel):
    userId: str
    sessionData: Optional[Dict[str, Any]] = None

@app.get("/")
def read_root():
    return {"status": "AI Detection Pipeline is running"}

@app.post("/analyze/text")
def analyze_text(req: TextAnalyzeRequest):
    """
    Analyze text to determine if it was generated by an AI (e.g., ChatGPT).
    """
    # NOTE: In a full production setup, you would load a HuggingFace Transformer model here.
    # e.g., pipeline("text-classification", model="roberta-base-openai-detector")
    
    text = req.text.lower()
    
    # Simple heuristic fallback for fast inference during development
    ai_phrases = ["as an ai", "language model", "openai", "i strongly advise", "it is important to note"]
    is_bot = any(phrase in text for phrase in ai_phrases)
    
    # Simulate a realistic prediction score
    score = 0.92 if is_bot else random.uniform(0.02, 0.15)
    
    return {
        "score": score,
        "isAI": is_bot or score > 0.5,
        "confidence": 0.85 if is_bot else 0.95
    }

@app.post("/analyze/media")
def analyze_media(req: MediaAnalyzeRequest):
    """
    Analyze images/videos to determine if they are AI-generated (e.g., Midjourney, DALL-E).
    """
    # NOTE: Here you would integrate an image classifier or deepfake detection model.
    if not req.urls:
        return {"score": 0, "isAI": False, "confidence": 1.0}
        
    return {
        "score": random.uniform(0.1, 0.3),
        "isAI": False,
        "confidence": 0.8
    }

@app.post("/analyze/behavior")
def analyze_behavior(req: BehaviorAnalyzeRequest):
    """
    Analyze user session and activity patterns to detect automated bot behavior.
    """
    # NOTE: In real-world, this would use an anomaly detection model on event streams.
    return {
        "score": random.uniform(0.05, 0.15),
        "isBotLikely": False,
        "confidence": 0.9
    }

# Backward compatibility for the generic /analyze endpoint used in the older server setup
@app.post("/analyze")
def analyze_generic(req: Dict[str, Any]):
    if "text" in req:
        return analyze_text(TextAnalyzeRequest(**req))
    elif "urls" in req:
        return analyze_media(MediaAnalyzeRequest(**req))
    elif "userId" in req:
        return analyze_behavior(BehaviorAnalyzeRequest(**req))
    else:
        raise HTTPException(status_code=400, detail="Invalid request payload. Expected 'text', 'urls', or 'userId'.")
